name: Update GitHub Stats

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install GitHub Stats
        run: npm install -g github-stats-card

      - name: Generate Stats Image
        run: |
          stats_image=$(github-stats-card --username sbreno101 --private)
          echo "$stats_image" > stats.png

      - name: Update README
        run: |
          echo "**Your existing README content here...**" >> README.md
          echo "![](stats.png)" >> README.md
          echo "**...More existing README content here**" >> README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
